const estoque = [
    {
        id: "bermuda-corteiz",
        categoria: "bermudas",
        nome: "Bermuda Corteiz",
        preco: "550",
        img: "img/jorts1.jpg", 
        composicao: "96% Algodão 4% Elastano",
        estampa: "Silk",
        etiqueta: "Gola",
        medidas: "M • 57 × 79 cm<br>G • 59 × 80 cm<br>GG • 63 × 83 cm"
    },
    {
        id: "bermuda-derschutze-blue",
        categoria: "bermudas",
        nome: "Bermuda Derschutze Blue",
        preco: "340",
        img: "img/jorts2.webp", 
        composicao: "100% Algodão",
        estampa: "Bordado",
        etiqueta: "Cós",
        medidas: "M • 55 × 77 cm<br>G • 58 × 79 cm<br>GG • 61 × 81 cm"
    },
    {
        id: "bermuda-derschutze-black",
        categoria: "bermudas",
        nome: "Bermuda Derschutze Black",
        preco: "340",
        img: "img/jorts3.jpg",
        composicao: "100% Algodão",
        estampa: "Bordado",
        etiqueta: "Cós",
        medidas: "M • 55 × 77 cm<br>G • 58 × 79 cm<br>GG • 61 × 81 cm"
    },
    {
        id: "calca-derschutze-1",
        categoria: "calcas",
        nome: "Calça Derschutze",
        preco: "500",
        img: "img/jeans1.jpg",
        composicao: "100% Algodão Denim",
        estampa: "Etiqueta Couro",
        etiqueta: "Cós",
        medidas: "38 • 102cm comprimento<br>40 • 104cm comprimento<br>42 • 106cm comprimento"
    },
    {
        id: "calca-derschutze-2",
        categoria: "calcas",
        nome: "Calça Derschutze",
        preco: "500",
        img: "img/jeans2.jpg",
        composicao: "100% Algodão Denim",
        estampa: "Etiqueta Couro",
        etiqueta: "Cós",
        medidas: "38 • 102cm comprimento<br>40 • 104cm comprimento<br>42 • 106cm comprimento"
    },
    {
        id: "calca-lodre-1",
        categoria: "calcas",
        nome: "Calça L'odre",
        preco: "450",
        img: "img/jeans3.webp",
        composicao: "100% Algodão",
        estampa: "Bordado",
        etiqueta: "Lateral",
        medidas: "P • 100cm<br>M • 103cm<br>G • 106cm"
    },
    {
        id: "calca-lodre-2",
        categoria: "calcas",
        nome: "Calça L'odre",
        preco: "450",
        img: "img/jeans4.webp",
        composicao: "100% Algodão",
        estampa: "Bordado",
        etiqueta: "Lateral",
        medidas: "P • 100cm<br>M • 103cm<br>G • 106cm"
    },
    {
        id: "calca-quadro-1",
        categoria: "calcas",
        nome: "Calça Quadro Creations",
        preco: "329",
        img: "img/jeans5.jpg",
        composicao: "Sarja Premium",
        estampa: "Silk",
        etiqueta: "Interna",
        medidas: "38 • 101cm<br>40 • 103cm<br>42 • 105cm"
    },
    {
        id: "calca-quadro-2",
        categoria: "calcas",
        nome: "Calça Quadro Creations",
        preco: "329",
        img: "img/jeans6.webp",
        composicao: "Sarja Premium",
        estampa: "Silk",
        etiqueta: "Interna",
        medidas: "38 • 101cm<br>40 • 103cm<br>42 • 105cm"
    },
    {
        id: "camisa-ch-1",
        categoria: "camisas",
        nome: "Camisa Chrome Hearts",
        preco: "6000",
        img: "img/ch1.webp",
        composicao: "100% Algodão Premium",
        estampa: "Silk Screen HD",
        etiqueta: "Gola e Lateral",
        medidas: "P • 54x72cm<br>M • 56x74cm<br>G • 58x76cm"
    },
    {
        id: "camisa-balenciaga-1",
        categoria: "camisas",
        nome: "Camisa Balenciaga",
        preco: "7000",
        img: "img/balenciaga1.jpeg",
        composicao: "Algodão Oversized",
        estampa: "Logomania",
        etiqueta: "Gola Bordada",
        medidas: "P • 60x78cm<br>M • 62x80cm<br>G • 64x82cm"
    },
    {
        id: "camisa-balenciaga-2",
        categoria: "camisas",
        nome: "Camisa Balenciaga",
        preco: "7000",
        img: "img/balenciaga2.jpg",
        composicao: "Algodão Oversized",
        estampa: "Logomania",
        etiqueta: "Gola Bordada",
        medidas: "P • 60x78cm<br>M • 62x80cm<br>G • 64x82cm"
    },
    {
        id: "camisa-mad-1",
        categoria: "camisas",
        nome: "Camisa Mad Enlatados",
        preco: "210",
        img: "img/mad1.avif",
        composicao: "100% Algodão",
        estampa: "Digital Print",
        etiqueta: "Gola",
        medidas: "P • 52x70cm<br>M • 54x72cm<br>G • 56x74cm"
    },
    {
        id: "camisa-mad-2",
        categoria: "camisas",
        nome: "Camisa Mad Enlatados",
        preco: "210",
        img: "img/mad2.jpg",
        composicao: "100% Algodão",
        estampa: "Digital Print",
        etiqueta: "Gola",
        medidas: "P • 52x70cm<br>M • 54x72cm<br>G • 56x74cm"
    },
    {
        id: "camisa-mad-3",
        categoria: "camisas",
        nome: "Camisa Mad Enlatados",
        preco: "210",
        img: "img/mad3.jpg",
        composicao: "100% Algodão",
        estampa: "Digital Print",
        etiqueta: "Gola",
        medidas: "P • 52x70cm<br>M • 54x72cm<br>G • 56x74cm"
    },
    {
        id: "camisa-derschutze-1",
        categoria: "camisas",
        nome: "Camisa Derschutze",
        preco: "320",
        img: "img/derschutze1.webp",
        composicao: "Algodão Pima",
        estampa: "Bordado Frontal",
        etiqueta: "Lateral",
        medidas: "M • 55x75cm<br>G • 57x77cm<br>GG • 59x79cm"
    },
    {
        id: "camisa-derschutze-2",
        categoria: "camisas",
        nome: "Camisa Derschutze",
        preco: "320",
        img: "img/derschutze2.jpg",
        composicao: "Algodão Pima",
        estampa: "Bordado Frontal",
        etiqueta: "Lateral",
        medidas: "M • 55x75cm<br>G • 57x77cm<br>GG • 59x79cm"
    },
    {
        id: "camisa-qc-1",
        categoria: "camisas",
        nome: "Camisa Quadro Creations",
        preco: "250",
        img: "img/qc1.webp",
        composicao: "Algodão Orgânico",
        estampa: "Silk",
        etiqueta: "Gola",
        medidas: "P • 53x71cm<br>M • 55x73cm<br>G • 57x75cm"
    },
    {
        id: "air-max-95-cdg",
        categoria: "sneakers",
        nome: "Air max 95 X CDG",
        preco: "1600",
        img: "img/air1.jpg",
        composicao: "Couro e Mesh",
        estampa: "Collab CDG",
        etiqueta: "Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm<br>44 • 29cm"
    },
    {
        id: "air-max-95-corteiz-1",
        categoria: "sneakers",
        nome: "Air max 95 X Corteiz",
        preco: "1200",
        img: "img/air2.jpg",
        composicao: "Sintético Premium",
        estampa: "Corteiz Alcatraz",
        etiqueta: "Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "air-max-95-corteiz-2",
        categoria: "sneakers",
        nome: "Air max 95 X Corteiz",
        preco: "1200",
        img: "img/air3.webp",
        composicao: "Sintético Premium",
        estampa: "Corteiz Alcatraz",
        etiqueta: "Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "air-max-95-preto",
        categoria: "sneakers",
        nome: "Air max 95 Preto",
        preco: "800",
        img: "img/air preto.jpg",
        composicao: "Couro e Tecido",
        estampa: "Refletivo",
        etiqueta: "Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "air-max-95-anatomy",
        categoria: "sneakers",
        nome: "Air max 95 Anatomy of Air",
        preco: "2000",
        img: "img/air5.jpg",
        composicao: "Mix de Materiais",
        estampa: "Especial Anatomy",
        etiqueta: "Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "asics-gel-nyc-1",
        categoria: "sneakers",
        nome: "ASICS GEL NYC",
        preco: "1400",
        img: "img/gel1.webp",
        composicao: "Camurça e Mesh",
        estampa: "GEL Technology",
        etiqueta: "Língua",
        medidas: "39 • 26cm<br>41 • 27.5cm<br>43 • 29cm"
    },
    {
        id: "asics-gel-nyc-2",
        categoria: "sneakers",
        nome: "ASICS GEL NYC",
        preco: "1400",
        img: "img/gel2.webp",
        composicao: "Camurça e Mesh",
        estampa: "GEL Technology",
        etiqueta: "Língua",
        medidas: "39 • 26cm<br>41 • 27.5cm<br>43 • 29cm"
    },
    {
        id: "asics-gel-nyc-3",
        categoria: "sneakers",
        nome: "ASICS GEL NYC",
        preco: "1400",
        img: "img/gel3.webp",
        composicao: "Camurça e Mesh",
        estampa: "GEL Technology",
        etiqueta: "Língua",
        medidas: "39 • 26cm<br>41 • 27.5cm<br>43 • 29cm"
    },
    {
        id: "asics-kayano-1",
        categoria: "sneakers",
        nome: "ASICS KAYANO 14",
        preco: "1300",
        img: "img/kayano1.webp",
        composicao: "Mesh e Sintético",
        estampa: "Performance",
        etiqueta: "Língua",
        medidas: "39 • 26cm<br>41 • 27.5cm<br>43 • 29cm"
    },
    {
        id: "asics-kayano-2",
        categoria: "sneakers",
        nome: "ASICS KAYANO 14",
        preco: "1300",
        img: "img/kayano2.webp",
        composicao: "Mesh e Sintético",
        estampa: "Performance",
        etiqueta: "Língua",
        medidas: "39 • 26cm<br>41 • 27.5cm<br>43 • 29cm"
    },
    {
        id: "asics-kayano-3",
        categoria: "sneakers",
        nome: "ASICS KAYANO 14",
        preco: "1300",
        img: "img/kayano3.jpeg",
        composicao: "Mesh e Sintético",
        estampa: "Performance",
        etiqueta: "Língua",
        medidas: "39 • 26cm<br>41 • 27.5cm<br>43 • 29cm"
    },
    {
        id: "nocta-hot-step-2",
        categoria: "sneakers",
        nome: "Nike Hot Step 2 x NOCTA",
        preco: "1800",
        img: "img/nocta1.webp",
        composicao: "Couro Sintético",
        estampa: "Chrome Details",
        etiqueta: "Interna/Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "nocta-af1",
        categoria: "sneakers",
        nome: "Nike AF1 x NOCTA Certified Lover Boy",
        preco: "1200",
        img: "img/nocta2.webp",
        composicao: "Couro Genuíno",
        estampa: "Love You Forever",
        etiqueta: "Calcanhar",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "nocta-glide",
        categoria: "sneakers",
        nome: "Nike x NOCTA Glide",
        preco: "1600",
        img: "img/nocta3.webp",
        composicao: "Têxtil e Sintético",
        estampa: "Carbon Fiber Look",
        etiqueta: "Língua",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "maison-mihara",
        categoria: "sneakers",
        nome: "MAISON MIHARA",
        preco: "3600",
        img: "img/outros1.webp",
        composicao: "Lona e Borracha",
        estampa: "Sole Solado",
        etiqueta: "Gorgurão",
        medidas: "37 • 25cm<br>39 • 26cm<br>41 • 27.5cm"
    },
    {
        id: "af1-cactus",
        categoria: "sneakers",
        nome: "AIR FORCE 1 CACTUS PLANT",
        preco: "1200",
        img: "img/outros2.jpg",
        composicao: "Couro Especial",
        estampa: "SUNSHINE",
        etiqueta: "Calcanhar",
        medidas: "38 • 25.5cm<br>40 • 26.5cm<br>42 • 28cm"
    },
    {
        id: "timberland",
        categoria: "sneakers",
        nome: "TIMBERLAND",
        preco: "600",
        img: "img/outros3.webp",
        composicao: "Nubuk",
        estampa: "Bordado Logo",
        etiqueta: "Lateral",
        medidas: "38 • 26cm<br>40 • 27cm<br>42 • 28.5cm"
    },
    {
        id: "rider-slx",
        categoria: "sneakers",
        nome: "RIDER SLX",
        preco: "400",
        img: "img/outros4.jpg",
        composicao: "Sintético",
        estampa: "Logo Rider",
        etiqueta: "Cinto",
        medidas: "38 • 25cm<br>40 • 26cm<br>42 • 27cm"
    }
];